# Building for Android requires API Level 24 or above.
# See https://apilevels.com

package:
  name: numpy
  version: 2.0.0 # 1.26.4

requirements:
 host:
#     - chaquopy-openblas 0.2.20
  - ninja
  - meson

build:
  script_env:
    NPY_DISABLE_SVML: 1
    #######################################################
    #  For iphone simulator Arm arch only
    # {% if sdk == 'iphonesimulator' and arch == 'arm64' %}
    LDFLAGS: -I/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator16.0.sdk/usr/include/ -mios-version-min=13.0
    CXXFLAGS: -I/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator16.0.sdk/usr/include/ -mios-version-min=13.0
    CPPFLAGS: -I/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator16.0.sdk/usr/include/ -mios-version-min=13.0
    #######################################################
    #  For iphone os Arm arch only
    # {% elif sdk == 'iphoneos' and arch == 'arm64' %}
    LDFLAGS: -I/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS16.0.sdk/usr/include -mios-version-min=13.0
    CXXFLAGS: -I/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS16.0.sdk/usr/include -mios-version-min=13.0
    CPPFLAGS: -I/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS16.0.sdk/usr/include -mios-version-min=13.0
    #######################################################
    #  For x86_64 arch only
    # {% elif sdk == 'iphonesimulator' and arch == 'x86_64' %}
    LDFLAGS: -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 
    CXXFLAGS: -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1
    CPPFLAGS: -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1
    #######################################################
    # {% endif %}


  backend-args:
    - -Csetup-args=-Dblas=none
    - -Csetup-args=-Dlapack=none
    - -Csetup-args=--cross-file
    - -Csetup-args={MESON_CROSS_FILE}    

  meson:
    properties:
# {% if sdk == 'android' and arch in ['arm64-v8a', 'x86_64'] %}
      longdouble_format: IEEE_QUAD_LE
# {% else %}
      longdouble_format: IEEE_DOUBLE_LE
# {% endif %}